const $ = (id) => {
  const element = document.getElementById(id);
  if (!element) {
    throw new Error(`Missing popup element: #${id}`);
  }
  return element;
};

export function getPopupElements() {
  return {
    urlList: $('urlList'),
    urlSection: $('urlSection'),
    urlListPane: $('urlListPane'),
    urlTemplatePane: $('urlTemplatePane'),
    urlCountBadge: $('urlCountBadge'),
    listModeButton: $('listModeButton'),
    templateModeButton: $('templateModeButton'),
    sequentialModeButton: $('sequentialModeButton'),
    urlTemplateLabel: $('urlTemplateLabel'),
    urlTemplateCountBadge: $('urlTemplateCountBadge'),
    urlTemplate: $('urlTemplate'),
    urlTemplateHistoryButton: $('urlTemplateHistoryButton'),
    urlTemplateClearButton: $('urlTemplateClearButton'),
    urlTemplateHistoryMenu: $('urlTemplateHistoryMenu'),
    urlTemplateItemsLabel: $('urlTemplateItemsLabel'),
    urlTemplateItems: $('urlTemplateItems'),
    urlTemplateItemsCountBadge: $('urlTemplateItemsCountBadge'),
    urlTemplateItemsHistoryButton: $('urlTemplateItemsHistoryButton'),
    urlTemplateItemsClearButton: $('urlTemplateItemsClearButton'),
    urlTemplateItemsHistoryMenu: $('urlTemplateItemsHistoryMenu'),
    showPreviewButton: $('showPreviewButton'),
    urlPreviewCount: $('urlPreviewCount'),
    urlPreviewPanel: $('urlPreviewPanel'),
    previewPanelSummary: $('previewPanelSummary'),
    previewPanelCloseButton: $('previewPanelCloseButton'),
    previewPanelList: $('previewPanelList'),
    extractLinksButton: $('extractLinksButton'),
    urlListHistoryButton: $('urlListHistoryButton'),
    urlListClearButton: $('urlListClearButton'),
    urlListHistoryMenu: $('urlListHistoryMenu'),
    linkSelectorPanel: $('linkSelectorPanel'),
    linkSelectorSummary: $('linkSelectorSummary'),
    linkSelectorCloseButton: $('linkSelectorCloseButton'),
    linkSelectorSearch: $('linkSelectorSearch'),
    linkSelectorAllButton: $('linkSelectorAllButton'),
    linkSelectorNoneButton: $('linkSelectorNoneButton'),
    linkSelectorInvertButton: $('linkSelectorInvertButton'),
    linkSelectorList: $('linkSelectorList'),
    linkSelectorCancelButton: $('linkSelectorCancelButton'),
    linkSelectorApplyButton: $('linkSelectorApplyButton'),
    captureSettings: $('captureSettings'),
    taskHistoryButton: $('taskHistoryButton'),
    taskHistoryPanel: $('taskHistoryPanel'),
    taskHistorySummary: $('taskHistorySummary'),
    taskHistoryRetryAllButton: $('taskHistoryRetryAllButton'),
    taskHistoryClearButton: $('taskHistoryClearButton'),
    taskHistoryList: $('taskHistoryList'),
    delay: $('delay'),
    schedulePanel: $('schedulePanel'),
    schedulePanelCloseButton: $('schedulePanelCloseButton'),
    scheduleTaskList: $('scheduleTaskList'),
    scheduleUrlPreview: $('scheduleUrlPreview'),
    scheduleAt: $('scheduleAt'),
    scheduleName: $('scheduleName'),
    scheduleButton: $('scheduleButton'),
    scheduleNewButton: $('scheduleNewButton'),
    scheduleSaveButton: $('scheduleSaveButton'),
    folder: $('folder'),
    currentTabButton: $('currentTabButton'),
    currentWindowTabsButton: $('currentWindowTabsButton'),
    settingsButton: $('settingsButton'),
    helpButton: $('helpButton'),
    openFillButton: $('openFillButton'),
    startButton: $('startButton'),
    pauseButton: $('pauseButton'),
    stopButton: $('stopButton'),
    statusText: $('statusText'),
    urlListLabelWrapper: $('urlListLabelWrapper'),
    urlSequentialPane: $('urlSequentialPane'),
    sequentialStartUrl: $('sequentialStartUrl'),
    sequentialStartUrlHistoryButton: $('sequentialStartUrlHistoryButton'),
    sequentialStartUrlClearButton: $('sequentialStartUrlClearButton'),
    sequentialStartUrlHistoryMenu: $('sequentialStartUrlHistoryMenu'),
    sequentialClearButton: $('sequentialClearButton'),
    sequentialNextSelector: $('sequentialNextSelector'),
    sequentialCaptureCount: $('sequentialCaptureCount'),
    detectNextPageButton: $('detectNextPageButton'),
    pickNextPageButton: $('pickNextPageButton'),
    dashboardPanel: $('dashboardPanel'),
    dashboardCloseButton: $('dashboardCloseButton'),
    dashboardProgressText: $('dashboardProgressText'),
    dashboardProgressBar: $('dashboardProgressBar'),
    dashboardLogList: $('dashboardLogList')
  };
}
